DROP DATABASE IF EXISTS itemCollector;

CREATE DATABASE itemCollector;

USE itemCollector;

CREATE TABLE user (
  id INT AUTO_INCREMENT NOT NULL,
  userName VARCHAR(150) NOT NULL,
  userPassword VARCHAR(150) NOT NULL,
  lastLogin DATETIME DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE categories (
  id INT AUTO_INCREMENT NOT NULL,
  category VARCHAR(150) NOT NULL,
  itemId VARCHAR(150) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE items (
  id INT AUTO_INCREMENT NOT NULL,
  itemName VARCHAR(150) NOT NULL,
  itemCondition VARCHAR(150) NOT NULL,
  itemQuantity INT(10) NOT NULL,
  itemDescription VARCHAR(300),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);